//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor.
// f-templa_res.rc

#define IDC_FROM_00                         2000
#define IDC_FROM_01                         2001
#define IDC_FROM_02                         2002
#define IDC_FROM_03                         2003
#define IDC_FROM_04                         2004
#define IDC_FROM_05                         2005
#define IDC_FROM_06                         2006
#define IDC_FROM_07                         2007
#define IDC_FROM_08                         2008
#define IDC_FROM_09                         2009
#define IDC_FROM_10                         2010
#define IDC_FROM_11                         2011
#define IDC_FROM_12                         2012
#define IDC_FROM_13                         2013
#define IDC_FROM_14                         2014
#define IDC_FROM_15                         2015
#define IDC_TO_00                           2100
#define IDC_TO_01                           2101
#define IDC_TO_02                           2102
#define IDC_TO_03                           2103
#define IDC_TO_04                           2104
#define IDC_TO_05                           2105
#define IDC_TO_06                           2106
#define IDC_TO_07                           2107
#define IDC_TO_08                           2108
#define IDC_TO_09                           2109
#define IDC_TO_10                           2110
#define IDC_TO_11                           2111
#define IDC_TO_12                           2112
#define IDC_TO_13                           2113
#define IDC_TO_14                           2114
#define IDC_TO_15                           2115
#define IDC_RARROW_00                       2200
#define IDC_RARROW_01                       2201
#define IDC_RARROW_02                       2202
#define IDC_RARROW_03                       2203
#define IDC_RARROW_04                       2204
#define IDC_RARROW_05                       2205
#define IDC_RARROW_06                       2206
#define IDC_RARROW_07                       2207
#define IDC_RARROW_08                       2208
#define IDC_RARROW_09                       2209
#define IDC_RARROW_10                       2210
#define IDC_RARROW_11                       2211
#define IDC_RARROW_12                       2212
#define IDC_RARROW_13                       2213
#define IDC_RARROW_14                       2214
#define IDC_RARROW_15                       2215
#define IDC_DARROW_00                       2300
#define IDC_DARROW_01                       2301
#define IDC_DARROW_02                       2302
#define IDC_DARROW_03                       2303
#define IDC_DARROW_04                       2304
#define IDC_DARROW_05                       2305
#define IDC_DARROW_06                       2306
#define IDC_DARROW_07                       2307
#define IDC_DARROW_08                       2308
#define IDC_DARROW_09                       2309
#define IDC_DARROW_10                       2310
#define IDC_DARROW_11                       2311
#define IDC_DARROW_12                       2312
#define IDC_DARROW_13                       2313
#define IDC_DARROW_14                       2314
#define IDC_DARROW_15                       2315
#define IDC_DARROW_PRESET                   2400

#define IDD_TOP                             100
#define IDD_SUBST                           101
#define IDD_INPUTBOX                        102
#define IDD_PRESET                          103

#define IDI_MAINICON                        100

#define IDS_APPNAME                         100
#define IDS_APPVERSION                      101
#define IDS_SELECTITEM                      102
#define IDS_TYPESUBST                       103
#define IDS_TODAY                           104
#define IDS_NOW                             105
#define IDS_THISYEAR                        106
#define IDS_USERNAME                        107
#define IDS_USERNAME2                       108
#define IDS_YEAR                            109
#define IDS_MONTH                           110
#define IDS_DAY                             111
#define IDS_HOUR                            112
#define IDS_MINUTE                          113
#define IDS_SECOND                          114
#define IDS_WEEKDAY                         115
#define IDS_WEEKDAYS                        116
#define IDS_SAVEPRESET                      117
#define IDS_ADDITEM                         118
#define IDS_NONE                            119
#define IDS_CANTDELETEFILE                  120
#define IDS_SECTIONAME                      121
#define IDS_INVALIDSTRING                   122
#define IDS_DONAME                          123
#define IDS_EDITPRESET                      124
#define IDS_DELETEKEYVALUE                  125

#define ID_REFRESH_SUBST                    100
#define ID_EDITPRESET                       101
#define ID_SAVEPRESET                       102
#define ID_ADDITEM                          103
#define ID_DELETEKEYANDVALUE                104

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     103
        #define _APS_NEXT_CONTROL_VALUE     2401
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
