//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor.
// f-templa_res.rc

#define IDD_TOP                             100
#define IDD_SUBST                           101
#define IDD_INPUTBOX                        102

#define IDI_MAINICON                        100

#define IDS_APPNAME                         100
#define IDS_APPVERSION                      101
#define IDS_SELECTITEM                      102
#define IDS_TYPESUBST                       103
#define IDS_TODAY                           104
#define IDS_NOW                             105
#define IDS_THISYEAR                        106
#define IDS_USERNAME                        107
#define IDS_YEAR                            108
#define IDS_MONTH                           109
#define IDS_DAY                             110
#define IDS_HOUR                            111
#define IDS_MINUTE                          112
#define IDS_SECOND                          113

#define ID_REFRESH_SUBST                    100

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     101
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
