//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor.
// FolderDeTempla_res.rc

#define IDD_TOP                             100
#define IDD_SUBST                           101
#define IDD_INPUTBOX                        102

#define IDI_MAINICON                        100

#define IDS_APPNAME                         100
#define IDS_APPVERSION                      101
#define IDS_SELECTITEM                      102
#define IDS_TYPESUBST                       103

#define ID_REFRESH_SUBST                    100

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     101
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
